spring:
#  数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 20030111
#  文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1000MB
#mybatis日志文件配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#阿里云oss
aliyun:
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    accessKeyId: "LTAI5t9XJ494wcipCfhm9ukC"
    accessKeySecret: ""
    bucketName: "spring-talis"
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
